version: '3.7'
services:
  jenkins:
    # build: ./
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - cisystem
    volumes:
      - my_jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket
      - /usr/bin/docker:/usr/bin/docker
    restart: always

networks:
  cisystem:

volumes:
  my_jenkins_home: